### ISSUE TITLE
Process CSV to accept user ID as parameter

### ISSUE THREAD

**Issue by aldnav** [casxai/gaminglounge#4]
https://github.com/casxai/gaminglounge/blob/adaedb4287950b0dd6d0c80c738be21a69dd48dc/GLbackend/dashboard/csv_processing.py#L16

Should `process_csv` then take another parameter `user_id`?

https://github.com/casxai/gaminglounge/blob/f1b6b118684730487e67ad979a5d25ca89ecde41/GLbackend/dashboard/views.py#L174C1-L174C30

Since this has an authenticated user, you can pass `request.user.id`

**Comment by casxai** [comment]
def process_csv(request, csv_file):

    user_id = str(request.user.id)
