### ISSUE TITLE
Potential 5xx on upload_csv

### ISSUE THREAD

**Issue by aldnav** [casxai/gaminglounge#5]
https://github.com/casxai/gaminglounge/blob/adaedb4287950b0dd6d0c80c738be21a69dd48dc/GLbackend/dashboard/views.py#L173C1-L176C72

does not catch exceptions. So it wouldn't reach `return JsonResponse({'message': 'File processed successfully'})`

Possible exceptions:

1. User not found
2. Wrong CSV parsing

**Comment by casxai** [comment]
@login_required
def upload_csv(request):
    try:
        if request.method == 'POST' and 'csv_file' in request.FILES: # Check if a file is uploaded
            csv_file = request.FILES['csv_file'] # Access the uploaded file
            
            process_csv(csv_file)
        
            return JsonResponse({'message': 'file processed successfully'})

    except FileNotFoundError:
        return JsonResponse({'error': 'csv file not found'}, status=404)
        
    except User.DoesNotExist:
        return JsonResponse({'error': 'user not found'}, status=404)

    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)

    return JsonResponse({'error': 'file upload failed'}, status=400)
