### ISSUE TITLE
Cache dashboard

### ISSUE THREAD

**Issue by aldnav** [casxai/gaminglounge#7]
https://github.com/casxai/gaminglounge/blob/adaedb4287950b0dd6d0c80c738be21a69dd48dc/GLbackend/dashboard/views.py#L25C1-L25C24

The `dashboard` has lots of DB queries for statistics. Although not much of the data is changing frequently. Should we consider caching the view?

Consider setting a reasonable cache duration. And also set the cache key (e.g. `dashboard`).

To invalidate the cache, or force refresh, we can designate a special view or a parameter to the `dashboard` view (e.g. `/dashboard/refresh=1`) then invoke `cache.delete("dashboard")`

Let me know your thoughts.

References:

1. https://docs.djangoproject.com/en/5.0/topics/cache/#the-per-view-cache

**Comment by casxai** [comment]
is it more ideal to use redis po ba instead of local memory cache for efficiency? kaso baka complicated po?

**Comment by casxai** [comment]
im not sure if tama po ung paggawa q

`from django.views.decorators.cache import cache_page
from django.core.cache import cache

@login_required
@cache_page(60 * 15) #cache for 15 minutes
def dashboard(request):
    
    if 'refresh' in request.GET:
        cache.delete('dashboard_view')
        return redirect('dashboard')
    
    admin = request.user
    # Total users count
    total_users_count = User.objects.count()`

**Comment by aldnav** [comment]
> is it more ideal to use redis po ba instead of local memory cache for efficiency? kaso baka complicated po?

Yes, but as you mentioned it will be more work to add Redis. For the meantime, you can use memcache and then move to Redis later if needed.

**Comment by aldnav** [comment]
> im not sure if tama po ung paggawa q
> 
> `from django.views.decorators.cache import cache_page from django.core.cache import cache
> 
> @login_required @cache_page(60 * 15) #cache for 15 minutes def dashboard(request):
> 
> ```
> if 'refresh' in request.GET:
>     cache.delete('dashboard_view')
>     return redirect('dashboard')
> 
> admin = request.user
> # Total users count
> total_users_count = User.objects.count()`
> ```

You can file a PR next time :)
